### ISSUE TITLE
点击日志出现服务错误

### ISSUE THREAD

**Issue by double2kill** [Mikelian320/JAVA-Mysql#18]
http://table.greatwebtech.cn/search/searchdata?searchMode=Log&SN=G1N40PP002696&PC_Name=BFEBFBFF000506E3&Record_Time=1558321157000&Slot=Slot+M1

Error:com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'Record_Time' in 'order clause'

**Comment by Mikelian320** [comment]
详细查询语句和报错信息
信息: SELECT LOG FROM ml_switch WHERE Slot='Slot+M1' AND SN='G1N40PP002696' AND PC_Name='BFEBFBFF000506E3' AND Record_Time='2019-05-20 10:59:17'  UNION SELECT LOG FROM securitypro WHERE Slot='Slot+M1' AND SN='G1N40PP002696' AND PC_Name='BFEBFBFF000506E3' AND Record_Time='2019-05-20 10:59:17'  ORDER BY Record_Time DESC limit 0,50
5月 13, 2020 9:30:11 下午 cn.greatwebtech.logger.LogExceptions afterThrowing
警告: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'Record_Time' in 'order clause'
